'use client';
import { upload } from '@vercel/blob/client';
import { FormEvent, useRef, useState } from 'react';

type BlobMeta = { url:string; pathname:string; contentType:string; size:number; filename:string };
export default function ReportForm(){const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [coords,setCoords]=useState('');const fileRef=useRef<HTMLInputElement>(null);
const locate=()=>{if(!navigator.geolocation){setMessage('Location is not available in this browser.');return}setMessage('Finding your location…');navigator.geolocation.getCurrentPosition(p=>{setCoords(`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`);setMessage('Exact location added. It will not be published in the public log.')},()=>setMessage('We could not access your location. You can continue with your PIN code.'));};
async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget);try{const pin=String(form.get('pin')||'');if(!/^\d{6}$/.test(pin))throw new Error('Please enter a valid 6-digit PIN code.');let attachments:BlobMeta[]=[];const files=Array.from(fileRef.current?.files||[]);if(files.length){const draft=crypto.randomUUID();attachments=await Promise.all(files.map(async file=>{const blob=await upload(`complaints/${draft}/${file.name}`,file,{access:'private',handleUploadUrl:'/api/blob/upload',clientPayload:JSON.stringify({submissionId:draft})});return {url:blob.url,pathname:blob.pathname,contentType:file.type,size:file.size,filename:file.name}}));}const [latitude,longitude]=coords?coords.split(',').map(x=>Number(x.trim())):[null,null];const response=await fetch('/api/complaints',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:form.get('title'),description:form.get('description'),category:form.get('category'),pin,email:form.get('email'),contact:form.get('contact'),latitude,longitude,attachments})});const data=await response.json();if(!response.ok)throw new Error(data.error);localStorage.setItem(`jansahay:token:${data.publicId}`,data.reporterToken);localStorage.setItem('jansahay:email',String(form.get('email')).toLowerCase());event.currentTarget.reset();setCoords('');setMessage(`Grievance ${data.publicId} was filed and routed to ${data.assignedAuthority}. You can manage closure or dispute the resolution in My portal.`)}catch(error){setMessage(error instanceof Error?error.message:'The grievance could not be submitted.')}finally{setBusy(false)}}
return <form className="form" onSubmit={submit}><label>Issue title *<input name="title" minLength={5} maxLength={180} required placeholder="e.g. Streetlight has been out for three weeks"/></label><label>Service category *<select name="category"><option value="water">Water & sanitation</option><option value="roads">Roads & transport</option><option value="power">Power & street lighting</option><option value="health">Health services</option><option value="housing">Housing & urban services</option><option value="other">Other public service</option></select></label><label className="full">What happened? *<textarea name="description" minLength={20} maxLength={5000} required placeholder="Describe the issue, when it began, and anything that would help the responsible team find it."/></label><label>PIN code *<input name="pin" inputMode="numeric" maxLength={6} required placeholder="110001"/></label><label>Email *<input name="email" type="email" required placeholder="you@example.com"/></label><label>Mobile (optional)<input name="contact" inputMode="tel" placeholder="For status notifications"/></label><label>Exact location (optional)<input value={coords} readOnly placeholder="Latitude, longitude"/></label><label className="full">Photos (optional; JPEG, PNG, WebP; up to 10 MB each)<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" multiple/></label><div className="full" style={{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><button type="button" className="action secondary" onClick={locate}>⌖ Use my exact location</button><button className="action" disabled={busy}>{busy?'Submitting…':'Submit grievance →'}</button></div>{message&&<div className={'notice full '+(message.includes('could not')||message.includes('Please')?'warn':'')}>{message}</div>}</form>}
