CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE complaint_status AS ENUM ('submitted','acknowledged','in_progress','resolved_by_authority','confirmed_closed','disputed','escalated','closed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE participant_role AS ENUM ('reporter','responsible_officer','system','moderator'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE event_type AS ENUM ('submitted','routed','acknowledged','progress_update','evidence_added','authority_marked_resolved','reporter_confirmed_closed','reporter_disputed','dispute_resolved','escalated'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS authorities (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, authority_type TEXT NOT NULL CHECK(authority_type IN ('ministry','department','state','municipality','utility')), jurisdiction_level TEXT NOT NULL CHECK(jurisdiction_level IN ('national','state','district','municipal','ward')), contact_email TEXT, contact_phone TEXT, public_url TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS representatives (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), full_name TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('minister','mp','mla','mayor','municipal_commissioner','responsible_officer')), constituency_or_jurisdiction TEXT, official_email TEXT, official_phone TEXT, office_address TEXT, public_url TEXT, authority_id UUID REFERENCES authorities(id), active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS service_categories (id TEXT PRIMARY KEY, name TEXT NOT NULL, parent_id TEXT REFERENCES service_categories(id), default_sla_days SMALLINT NOT NULL CHECK(default_sla_days > 0));
CREATE TABLE IF NOT EXISTS jurisdiction_rules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), pin_prefix TEXT NOT NULL CHECK(pin_prefix ~ '^[0-9]{1,6}$'), category_id TEXT REFERENCES service_categories(id), authority_id UUID NOT NULL REFERENCES authorities(id), priority SMALLINT NOT NULL DEFAULT 100, UNIQUE(pin_prefix,category_id,priority));
CREATE TABLE IF NOT EXISTS complaints (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(), public_id TEXT UNIQUE NOT NULL, reporter_access_hash TEXT NOT NULL, reporter_email TEXT NOT NULL, title TEXT NOT NULL CHECK(char_length(title) BETWEEN 5 AND 180), description TEXT NOT NULL CHECK(char_length(description) BETWEEN 20 AND 5000), category_id TEXT NOT NULL REFERENCES service_categories(id), pin_code CHAR(6) NOT NULL CHECK(pin_code ~ '^[0-9]{6}$'), latitude NUMERIC(9,6), longitude NUMERIC(9,6), location_precision_m SMALLINT, public_geohash TEXT, contact_phone TEXT, assigned_authority_id UUID REFERENCES authorities(id), status complaint_status NOT NULL DEFAULT 'submitted', sla_due_at TIMESTAMPTZ, submitted_at TIMESTAMPTZ NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ, closed_at TIMESTAMPTZ, CHECK((latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)));
CREATE INDEX IF NOT EXISTS complaints_public_log_idx ON complaints(status,submitted_at DESC); CREATE INDEX IF NOT EXISTS complaints_geo_idx ON complaints(public_geohash,category_id,submitted_at DESC); CREATE INDEX IF NOT EXISTS complaints_authority_idx ON complaints(assigned_authority_id,status);
CREATE TABLE IF NOT EXISTS attachments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), complaint_id UUID NOT NULL REFERENCES complaints(id) ON DELETE CASCADE, blob_url TEXT NOT NULL, blob_pathname TEXT NOT NULL, content_type TEXT NOT NULL, byte_size INTEGER NOT NULL CHECK(byte_size > 0), original_filename TEXT NOT NULL, visibility TEXT NOT NULL DEFAULT 'private' CHECK(visibility IN ('private','authority_only','public_redacted')), uploaded_by participant_role NOT NULL DEFAULT 'reporter', uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS complaint_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), complaint_id UUID NOT NULL REFERENCES complaints(id) ON DELETE CASCADE, event_type event_type NOT NULL, actor_role participant_role NOT NULL, actor_representative_id UUID REFERENCES representatives(id), public_note TEXT, private_note TEXT, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS complaint_events_log_idx ON complaint_events(complaint_id,created_at ASC);
CREATE TABLE IF NOT EXISTS disputes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), complaint_id UUID NOT NULL UNIQUE REFERENCES complaints(id) ON DELETE CASCADE, raised_by participant_role NOT NULL DEFAULT 'reporter', reason TEXT NOT NULL CHECK(char_length(reason) BETWEEN 10 AND 3000), status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','under_review','upheld','rejected','withdrawn')), reviewed_by UUID REFERENCES representatives(id), resolution_note TEXT, opened_at TIMESTAMPTZ NOT NULL DEFAULT now(), resolved_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS public_contact_publications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), representative_id UUID REFERENCES representatives(id), authority_id UUID REFERENCES authorities(id), verified_at TIMESTAMPTZ NOT NULL, source_url TEXT NOT NULL, is_current BOOLEAN NOT NULL DEFAULT true, CHECK(representative_id IS NOT NULL OR authority_id IS NOT NULL));
CREATE OR REPLACE VIEW public_complaint_log AS SELECT c.public_id,c.title,sc.name AS category,c.status,c.public_geohash,c.submitted_at,c.resolved_at,a.name AS assigned_authority,COALESCE(count(d.id),0)>0 AS has_dispute FROM complaints c JOIN service_categories sc ON sc.id=c.category_id LEFT JOIN authorities a ON a.id=c.assigned_authority_id LEFT JOIN disputes d ON d.complaint_id=c.id GROUP BY c.id,sc.name,a.name;
